#ifndef _SE_FIELDTYPE_H
#define _SE_FIELDTYPE_H 

enum FieldType
{
    EN_BOOL_FIELD,
    EN_UINT8_FIELD,
    EN_UINT16_FIELD,
    EN_UINT32_FIELD,
    EN_UINT64_FIELD,
    EN_SINT8_FIELD,
    EN_SINT16_FIELD,
    EN_SINT32_FIELD,
    EN_SINT64_FIELD,
    EN_FLOAT_FIELD,
    EN_DOUBLE_FIELD,
    EN_ENUM_FIELD,
    EN_STRING_FIELD,
    EN_ARRAY_FIELD,
    EN_MAP_FIELD,
    EN_USER_FIELD,
    EN_MAX_FIELD
};
#endif

